# permissions for end users to view ztservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ztservice-viewer-role
rules:
- apiGroups:
  - zt.takutakahashi.dev
  resources:
  - ztservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zt.takutakahashi.dev
  resources:
  - ztservices/status
  verbs:
  - get
